version: "3.8"

services:
  silicon-brief:
    build: .
    container_name: silicon-brief

    env_file:
      - .env

    volumes:
      - ./data:/root/data
      - ./silicon-brief.db:/root/silicon-brief.db

    restart: unless-stopped
